### ISSUE TITLE
Problem with initializing a ResponsiveImage just with a placeholder

### ISSUE THREAD

**Issue by MitkoTschimev** [thisissoon/angular-image-loader#17]
If i want to initialize a ResponsiveImage just with a placeholder (image data are coming async from a backend) i get an error because it tries to read from that array images.

I created a PR for it with an example and tests. Please take a look there an tell me what you think.

https://github.com/thisissoon/angular-image-loader/pull/16

**Comment by edoparearyee** [comment]
@tfiwm I have merged that PR which should be available in v5.1.0

`npm i @thisissoon/angular-image-loader@5.1.0`
